[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
lib_deps =
    mikem/RadioHead@^1.120.0
    https://github.com/kokke/tiny-AES-c.git
    bblanchon/ArduinoJson@^7.0.0
    olikraus/U8g2@^2.35.9
    links2004/WebSockets@^2.4.0