"""add_matches_table

Revision ID: 290aef968940
Revises: dcfa03b93c5e
Create Date: 2026-05-21 13:57:53.946391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "290aef968940"
down_revision: Union[str, Sequence[str], None] = "dcfa03b93c5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("player_1_id", sa.BigInteger(), nullable=False),
        sa.Column("player_2_id", sa.BigInteger(), nullable=False),
        sa.Column("player_1_health", sa.SmallInteger(), nullable=True),
        sa.Column("player_2_health", sa.SmallInteger(), nullable=True),
        sa.Column("move", sa.String(length=64), nullable=True),
        sa.Column("time_from_start", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("player_effect", sa.String(length=64), nullable=True),
        sa.Column("event_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("player_1_id <> player_2_id", name="different_players"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_1_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_2_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(op.f("events_node_id_fkey"), "events", type_="foreignkey")
    op.drop_constraint(op.f("heartbeats_node_id_fkey"), "heartbeats", type_="foreignkey")
    op.drop_constraint(op.f("tamper_events_node_id_fkey"), "tamper_events", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f("tamper_events_node_id_fkey"), "tamper_events", "nodes", ["node_id"], ["node_id"])
    op.create_foreign_key(op.f("heartbeats_node_id_fkey"), "heartbeats", "nodes", ["node_id"], ["node_id"])
    op.create_foreign_key(op.f("events_node_id_fkey"), "events", "nodes", ["node_id"], ["node_id"])
    op.drop_table("matches")
    # ### end Alembic commands ###
