"""tilt readings table

Revision ID: 640aedf83138
Revises: 7fabb90fedac
Create Date: 2026-05-26 11:16:40.978041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "640aedf83138"
down_revision: Union[str, Sequence[str], None] = "7fabb90fedac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tilt_readings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=False),
        sa.Column("sequence_num", sa.SmallInteger(), nullable=False),
        sa.Column("node_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("lastx", sa.BigInteger(), nullable=True),
        sa.Column("lasty", sa.BigInteger(), nullable=True),
        sa.Column("lastz", sa.BigInteger(), nullable=True),
        sa.Column("received_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tilt_readings")
    # ### end Alembic commands ###
