"""remove training samples code

Revision ID: 7fabb90fedac
Revises: d901a91722b9
Create Date: 2026-05-26 09:51:52.495806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7fabb90fedac"
down_revision: Union[str, Sequence[str], None] = "d901a91722b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_samples")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_samples",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "label",
            postgresql.ENUM("background", "attack", "defense", name="event_class"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("peak_amplitude", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("rms_energy", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("zcr", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("decay_ms", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column(
            "collected_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("training_samples_pkey")),
    )
    # ### end Alembic commands ###
