"""bigint

Revision ID: fa25e9709f9f
Revises: 98e3ef0ce5fb
Create Date: 2026-05-26 15:30:21.087049

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa25e9709f9f"
down_revision: Union[str, Sequence[str], None] = "98e3ef0ce5fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events", "sequence_num", existing_type=sa.SMALLINT(), type_=sa.BigInteger(), existing_nullable=False
    )
    op.alter_column(
        "tilt_readings", "sequence_num", existing_type=sa.SMALLINT(), type_=sa.BigInteger(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tilt_readings", "sequence_num", existing_type=sa.BigInteger(), type_=sa.SMALLINT(), existing_nullable=False
    )
    op.alter_column(
        "events", "sequence_num", existing_type=sa.BigInteger(), type_=sa.SMALLINT(), existing_nullable=False
    )
    # ### end Alembic commands ###
