"""add last_x_y_z to events

Revision ID: c1ab0ed0ad93
Revises: 290aef968940
Create Date: 2026-05-22 13:09:24.207362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1ab0ed0ad93"
down_revision: Union[str, Sequence[str], None] = "290aef968940"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("lastx", sa.BigInteger(), nullable=True))
    op.add_column("events", sa.Column("lasty", sa.BigInteger(), nullable=True))
    op.add_column("events", sa.Column("lastz", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "lastz")
    op.drop_column("events", "lasty")
    op.drop_column("events", "lastx")
    # ### end Alembic commands ###
