"""remove tamper events table

Revision ID: fa0309d34570
Revises: 640aedf83138
Create Date: 2026-05-26 12:06:25.580514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa0309d34570"
down_revision: Union[str, Sequence[str], None] = "640aedf83138"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tamper_events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tamper_events",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("node_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("ldr_value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column(
            "triggered_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("resolved_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("tamper_events_pkey")),
    )
    # ### end Alembic commands ###
