"""add user_id to game

Revision ID: 5b34a8509a50
Revises: c09d00e8d431
Create Date: 2026-05-28 10:48:58.013398

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b34a8509a50"
down_revision: Union[str, Sequence[str], None] = "c09d00e8d431"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "games", "users", ["user_id"], ["id"])
    op.drop_index(op.f("users_email_unique_idx"), table_name="users")
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.create_index(op.f("users_email_unique_idx"), "users", ["email"], unique=True)
    op.drop_constraint(None, "games", type_="foreignkey")
    op.drop_column("games", "user_id")
    # ### end Alembic commands ###
