"""add_game_summary_table

Revision ID: 03babab07eb3
Revises: fa25e9709f9f
Create Date: 2026-05-27 14:29:47.953820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03babab07eb3"
down_revision: Union[str, Sequence[str], None] = "fa25e9709f9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_summaries",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("game_id", sa.BigInteger(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("avg_tilt_magnitude", sa.Float(), nullable=False),
        sa.Column("x_bias", sa.Float(), nullable=False),
        sa.Column("tilt_variance", sa.Float(), nullable=False),
        sa.Column("sharp_reversals", sa.BigInteger(), nullable=False),
        sa.Column("max_tilt_angle_deg", sa.Float(), nullable=False),
        sa.Column("packet_loss_rate", sa.Float(), nullable=False),
        sa.Column("outcome", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_summaries")
    # ### end Alembic commands ###
