"""fk_nodes

Revision ID: 4a268a0b6979
Revises: d3371231d69e
Create Date: 2026-05-26 14:08:23.995795

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4a268a0b6979"
down_revision: Union[str, Sequence[str], None] = "d3371231d69e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "tilt_readings", "nodes", ["node_id"], ["node_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tilt_readings", type_="foreignkey")
    # ### end Alembic commands ###
