"""add end reason

Revision ID: a9352e95809b
Revises: 4e8e0c340c86
Create Date: 2026-05-26 14:47:58.896796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9352e95809b"
down_revision: Union[str, Sequence[str], None] = "4e8e0c340c86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("end_reason", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "end_reason")
    # ### end Alembic commands ###
