"""remove_matches_table

Revision ID: d901a91722b9
Revises: c1ab0ed0ad93
Create Date: 2026-05-26 09:32:55.876400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d901a91722b9"
down_revision: Union[str, Sequence[str], None] = "c1ab0ed0ad93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matches")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("player_1_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("player_2_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("player_1_health", sa.SMALLINT(), autoincrement=False, nullable=True),
        sa.Column("player_2_health", sa.SMALLINT(), autoincrement=False, nullable=True),
        sa.Column("move", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column(
            "time_from_start",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("player_effect", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("event_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.CheckConstraint("player_1_id <> player_2_id", name=op.f("different_players")),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], name=op.f("matches_event_id_fkey")),
        sa.ForeignKeyConstraint(["player_1_id"], ["users.id"], name=op.f("matches_player_1_id_fkey")),
        sa.ForeignKeyConstraint(["player_2_id"], ["users.id"], name=op.f("matches_player_2_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("matches_pkey")),
    )
    # ### end Alembic commands ###
