"""add  game table

Revision ID: 4e8e0c340c86
Revises: 4a268a0b6979
Create Date: 2026-05-26 14:35:00.255367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e8e0c340c86"
down_revision: Union[str, Sequence[str], None] = "4a268a0b6979"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("games", sa.Column("id", sa.BigInteger(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.add_column("tilt_readings", sa.Column("game_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "tilt_readings", "games", ["game_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tilt_readings", type_="foreignkey")
    op.drop_column("tilt_readings", "game_id")
    op.drop_table("games")
    # ### end Alembic commands ###
